# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: [pytest-check]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
        files: pyproject\.toml$
        types: [ file ]
        args: [ --lock ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        files: \.py$
        types: [ file ]
        args: [ --fix ]
      - id: ruff-format
        files: \.py$
        types: [ file ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-ujson

  - repo: local
    hooks:
      - id: pytest-check
        # stages: [ pre-push ]
        types: [ python ]
        name: pytest-check
        entry: poetry run python -m pytest tests
        language: system
        pass_filenames: false
        always_run: true
