name: Release package to PyPI

on:
  release:
    types: [ published, created ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Publish draft to Test PyPI
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi "${{ secrets.TEST_PYPI_TOKEN }}"
          poetry publish --build -r testpypi

      - name: Publish to PyPI
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"
          poetry publish --build
